name: scripts
version: 0.1.0

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text

executables:
  verify-bintray-upload:
    main: verify-bintray-upload.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - turtle
      - system-filepath
      - pseudomacros
      - megaparsec
      - bifunctors
      - managed
